const AZURE_API_ENDPOINT = process.env.AZURE_API_ENDPOINT || "";
const AZURE_API_KEY = process.env.AZURE_API_KEY || "";
const STABILITY_AI_API_KEY = process.env.STABILITY_AI_API_KEY || "";
const STABILITY_AI_API_ENDPOINT = process.env.STABILITY_AI_API_ENDPOINT || "";

export {AZURE_API_ENDPOINT, AZURE_API_KEY, STABILITY_AI_API_ENDPOINT, STABILITY_AI_API_KEY}